export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";

export const INCREASE = "SET_INCREASE";
export const DECREASE = "SET_DECRESE";

export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";
export const GET_ONE_PAYMENT = "GET_ONE_PAYMENT";
export const DELETE_ONE_PAYMENT = "DELETE_ONE_PAYMENT";
export const UPDATE_ONE_PAYMENT = "UPDATE_ONE_PAYMENT";
export const CREATE_ONE_PAYMENT = "CREATE_ONE_PAYMENT";
export const PAYMENT_LOADING = "PAYMENT_LOADING";
export const PAYMENT_LOADING_OFF = "PAYMENT_LOADING_OFF";
export const RESET_PAYMENT_DATA = "RESET_PAYMENT_DATA";
